### ISSUE TITLE
Please publish latest version to npm

### ISSUE THREAD

**Issue by HAKASHUN** [whzhyh/gitbook-plugin-toc#10]
The latest version is 0.0.2, but the version on npm is 0.0.1.
Please run npm publish! Thanks :-)

**Comment by willin** [comment]
https://www.npmjs.com/package/gitbook-plugin-toc

**Comment by willin** [comment]
请把我加到项目成员

**Comment by whzhyh** [comment]
added

**Comment by willin** [comment]
我说的是npmjs.com上,该push更新了

**Comment by jashaj** [comment]
Version of this plugin 0.0.1 doesn't work on Node 7 or up. It would be great if this updated version was published to npmjs.com. Can you please publish it?

**Comment by willin** [comment]
@jashaj gitbook-plugin-atoc

**Comment by whzhyh** [comment]
published
