### ISSUE TITLE
Alternate trigger

### ISSUE THREAD

**Issue by mlopezgva** [whzhyh/gitbook-plugin-toc#14]
Is it possible to use a more spread trigger token for this feature?

I'm looking for the "best" markdown editor. I've found that at least three editors use th e`[TOC]` "markdown" to insert the **Table of Contents**. I know there's no "official" markdown for TOC, but I also think this is a much better mark: simple, portable (since many others already use it) and expressive (a block [ ] containing the TOC).

Thanks for reading.

**Comment by billryan** [comment]
@mlopezgva  `<!-- toc -->` is used in https://github.com/jonschlinkert/markdown-toc, I think it is the reason why so many author wrote toc plugin using this token.
I think it is better to generate toc automatically but you can control the depth. ==> https://github.com/billryan/gitbook-plugin-etoc

**Comment by mlopezgva** [comment]
After some thinking, I understand that using the `toc` inside _html comment tag_ is useful: it won't appear rendered if the MD implementation doesn't support it. Thanks.
